Banana

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -35,8 +35,8 @@ jobs:
             sleep 60
             docker ps
             docker exec ogp_web_1 "/docker-health.sh"
-            if [ "curl -ks --head http://localhost:10001/install.php" ]; then
-              echo "bananas"
+            if [ ! "curl -ks --head http://localhost:10001/install.php" ]; then
+              exit 1 # FAILURE
             fi
 
             # docker exec ogp_web_1 "if [ ! -f '/var/www/html/install.php' ]; then exit 1; fi"
